export const IS_SPLASH = 'IS_SPLASH';
export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST'
export const SIGN_UP_SUCESS = 'SIGN_UP_SUCESS'
export const SIGN_UP_FAIL = 'SIGN_UP_FAIL'
export const GET_USER_DATA_REQUEST = 'GET_USER_DATA_REQUEST'
export const CLEAR_USER_DATA_REQUEST = 'CLEAR_USER_DATA_REQUEST'
export const CLEAR_SUCESS = 'CLEAR_SUCESS'



