export const IS_SPLASH = 'IS_SPLASH';
export const SAVE_USER_DATA = 'SAVE_USER_DATA';
export const PROGRESS_UPDATE = 'PROGRESS_UPDATE';
export const IS_LOGOUT = 'IS_LOGOUT'
export const IS_BOTTOM_BAR = 'IS_BOTTOM_BAR'
export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST'
export const SIGN_UP_SUCESS = 'SIGN_UP_SUCESS'
export const SIGN_UP_FAIL = 'SIGN_UP_FAIL'
export const GET_USER_DATA_REQUEST = 'GET_USER_DATA_REQUEST'
export const CLEAR_USER_DATA_REQUEST = 'CLEAR_USER_DATA_REQUEST'




